language: python

install:
  - pip install tox-travis
  - pip install -r requirements.txt
matrix:
  include:
    - python: 3.7
      env:
        - TOX_ENV=py37
    - python: 3.6
      env:
        - TOX_ENV=py36
    - python: 3.5
      env:
        - TOX_ENV=py35
script:
  - flask run &
  - tox
